name: umeng
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:

  fl_umeng:
    path: ../
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
