name: fl_umeng
description: umeng plugin for flutter, only Android and IOS are supported
version: 1.0.0
repository: https://github.com/Wayaer/fl_umeng.git

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: flutter.umeng
        pluginClass: UmengPlugin
      ios:
        pluginClass: UmengPlugin
